optimizer: {
  type: AdamW,
  kwargs: {
    lr: 0.001,
    weight_decay: 0.1
  } }

scheduler: {
  type: CosLR,
  kwargs: {
    epochs: 300,
    initial_epochs: 30
  } }

dataset: {
  train: { _base_: cfgs/dataset_configs/ModelNet40.yaml,
           others: { subset: 'train' } },
  val: { _base_: cfgs/dataset_configs/ModelNet40.yaml,
         others: { subset: 'test' } },
  test: { _base_: cfgs/dataset_configs/ModelNet40.yaml,
          others: { subset: 'test' } } }
model: {
  NAME: SpikePointMamba,
  trans_dim: 384,
  depth: 12,
  cls_dim: 40,
  num_heads: 6,
  group_size: 32,
  num_group: 128,
  encoder_dims: 384,
  rms_norm: False,
  drop_path: 0.3,
  drop_out: 0.,
  label_smoothing: 0.2,
  spike_mode: "lif",
  timestep: 2,
  expand: 1.1,  # Q-SDE++ hyper-parameter
}


npoints: 1024
total_bs: 144
step_per_update: 1
max_epoch: 300
grad_norm_clip: 10